# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsletterrecipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipients',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
